name: Check for new releases of docker/cli
on:
  schedule:
    - cron: '55 8 * * *'
  workflow_dispatch: {}

permissions:
  issues: write

jobs:
  check-docker-cli:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - run: npm ci

      - run: npm run dcmonitor
        env:
          GITHUB_TOKEN: ${{ secrets.RUN_WORKFLOW_FROM_WORKFLOW }}
