name: Test

on:
  push: {}
  pull_request: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: false
    - uses: actions/setup-node@v3
      with:
        node-version: '16.x'
    - uses: actions/setup-go@v3
      with:
        go-version: '^1.18'
    - run: npm ci
    - run: npm run lint:nofix
    - run: npm test
